title: Wired Brain Coffee
logo: "/images/company-logo.png?raw=true"
description: >
  first description
  <br><br>
  60 State Street
  Suite 800
  Boston, MA 02109
  <br><br>
  <a href="https://www.pluralsight.com">www.wiredbraincoffee.com</a>

theme: jekyll-theme-minimal

version: '2.0'
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
      
      steps:
        -checkout
        
        -run:
          name: Greeting
          command: echo Hello, world.
          
        -run:
          name: PrintCurTime
          command: date
